[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
darkpool_solana = "5FPrCjrhxkfm8dR79gPrCfYVYuJ7iUdpdZLLUMtZUwXR"
token_contract = "6HEsfvvUtEDgpu3214E4Chf9boYX28WJ8spbpvsvZDZJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000 # Increase this value (in milliseconds)